### ISSUE TITLE
Git shows sometimes the changes and sometimes not

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/zapp.run#1]
**Project ID (e.g. `flutter-123456`)**: I don't know anymore. I think it was just `edit/flutter`
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: 12.2.1
**Browser & Version (e.g. `Chome 102.0.5005.115`)**: 102.0.5005.115 (Official Build) (arm64)

### Demo

https://user-images.githubusercontent.com/24459435/175002293-e5b86e97-a151-4b44-8483-2cceef6ff278.mov

I'm not able to reproduce it anymore. I'm not sure if this is because I hit the "Save" button 🤔

**Comment by Salakar** [comment]
Please try the latest release out  this should be fixed, thanks
