### ISSUE TITLE
support `wrap with widget` 

### ISSUE THREAD

**Issue by Anas35** [invertase/zapp.run#111]
**Is your feature request related to a problem? Please describe.**
While developing, It often requires to wrap a widget or remove a widget from existing widget tree.

**Additional context**

![wrap](https://user-images.githubusercontent.com/65850618/213480030-c72b26de-1d16-4676-9a51-abbb61cde715.png)

**Comment by Ehesp** [comment]
You can do this already:

![image](https://user-images.githubusercontent.com/842078/213482501-02d73ebd-63c2-4d91-b689-21943d70e08b.png)

On your widget, `Cmd + .` - what did you do on Dartpad to get that to show?

**Comment by Anas35** [comment]
oh! didn't know that. On Dartpad, its `alt + enter`.

**Comment by Anas35** [comment]
may be, Add all the shortcuts keys to shortcuts screen in zapp. Currently, It show only four shortcuts key commands.

**Comment by Ehesp** [comment]
Yeah shortcuts are somewhat of a challenging topic right now.

Currently we use the built in VSCode bindings, however a lot of people also have IntelliJ bindings, but we're still working through some bugs and figuring out how to extract the bindings to display them.

**Comment by Ehesp** [comment]
Closing in favour of https://github.com/invertase/zapp.run/issues/75
