### ISSUE TITLE
Entry file selector not working

### ISSUE THREAD

**Issue by Salakar** [invertase/zapp.run#127]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description

Entry file drop-down next to run does not function correctly, run always seems to run lib/main.dart. Discovery of entrypoints is fine and working, selecting an entry in the dropdown list however does not persist to the signal (or at least reading it before being sent to compiler is on the old value).

**Comment by Ehesp** [comment]
https://github.com/invertase/zapp/commit/261e4956b6d9713cad022ae77cf03ff0529799c6
