### ISSUE TITLE
Dependencies panel leaking into editor

### ISSUE THREAD

**Issue by Salakar** [invertase/zapp.run#128]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description

![image](https://user-images.githubusercontent.com/5347038/217233088-8fddcfd4-a100-4110-8939-c03d4de4ba13.png)

**Comment by Ehesp** [comment]
Fixed
