### ISSUE TITLE
Change dash to underscores while downloading Zapp

### ISSUE THREAD

**Issue by mhadaily** [invertase/zapp.run#129]
When you are downloading a Zapp it follows the package ID or URL that comes with standard `-`. However, the package name with `-` is not valid name. 

While this is not a big deal but it's nice to change Zapp folder name (package name) to follow the convention so when you download and wanna run, you don't get an error that says package name is not valid. 

https://zapp.run/edit/extensions-workshop-zgmg064igmh0?entry=lib/main.dart&file=lib/pages/home_page.dart
Example extensions-workshop- zgmg064igmh0 to extensions_workshop_zgmg064igmh0

**Comment by Ehesp** [comment]
Deployed
