### ISSUE TITLE
Curious about how Zapp is run without fees?

### ISSUE THREAD

**Issue by mojtabana** [invertase/zapp.run#131]
Hey folks!
I am really curious about how this is possible to build something for free?
I am developing some app but due to massive server costs I can't handle it! 
can somebody tell me how I can deliver service for free like Zapp?

**Comment by Ehesp** [comment]
The majority of Zapp currently runs in the browser. We have some backend services to handle authentication, fetching project data etc but these costs are fairly minimal.

**Comment by mojtabana** [comment]
sounds good.
Thanks for your response.
