### ISSUE TITLE
I cant enter to flutter ide

### ISSUE THREAD

**Issue by mehrdaddjavdi** [invertase/zapp.run#132]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

**Comment by Ehesp** [comment]
Please provide some more details.

**Comment by Ken-Andre** [comment]
Me too now
![image](https://github.com/invertase/zapp.run/assets/105988844/e557af43-b074-4b8f-9342-3df0e92963b0)
