### ISSUE TITLE
Package import is not working as expected

### ISSUE THREAD

**Issue by immadisairaj** [invertase/zapp.run#133]
**Project ID (e.g. `flutter-123456`)**: Not required
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: macOS Ventura 13.2.1
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Safari 16.3

### Description

I have a package that I wanted to import directly to Zapp. But, it shows me the following error even if the package is supported for web:
<img width="792" alt="Screenshot 2023-03-09 at 13 43 25" src="https://user-images.githubusercontent.com/40348358/223960856-37c30992-cfe3-4946-a8e9-2917e5e3f22c.png">

Package: [Prides](https://pub.dev/packages/prides)

### Additional Info:

I had tried previously first. But, the example project had greater sdk version (created using flutter master). So, I have fixed the issue.

**Comment by Ehesp** [comment]
This seems to be working for me: https://zapp.run/pub/prides?entry=lib/main.dart&file=lib/main.dart

**Comment by Ehesp** [comment]
Looks like the package is quite new - it might have been an issue where when it was published, pub was still analyzing the project and thus when Zapp checks it via the pub API it wasn't available yet (or something).

**Comment by immadisairaj** [comment]
Yep. I had recently published the package. I had tried it after the analysis was done. Maybe it had took some time to update and I wasn't able to run it. Thank you.. Now it works well.. You can close this issue.

**Comment by Ehesp** [comment]
We do have some caching internally going on, so might have just hit that. Will close it, but keep an eye out for related issues. 

Cool project though btw - works well.
