### ISSUE TITLE
How do you sign out of your GitHub account on Zapp?

### ISSUE THREAD

**Issue by SteveBraich** [invertase/zapp.run#151]
I have two GitHub accounts.  One for work and one for school.  

How do I switch which GitHub account my Zapp session is connected to?

**Comment by Ehesp** [comment]
Hi,

In the editor you can click your avatar:

![image](https://github.com/invertase/zapp.run/assets/842078/2d1e3292-8dd1-446e-bd0e-ffa42b23a4e2)
