### ISSUE TITLE
Support opening app full-screen in another tab

### ISSUE THREAD

**Issue by blaugold** [invertase/zapp.run#21]
This would give the editor and the app more space when multiple screens are available, and would be useful when the app layout does not work well in the space next to the editor.

The app should reload in the other tab when clicking "Build".

**Comment by Ehesp** [comment]
Okay I've moved the run button to the top now so it's not impacted by the preview pane - will take a look at pop out support at some point then.

**Comment by Ehesp** [comment]
Going to close this one as it's directly related to the work in https://github.com/invertase/zapp.run/issues/39
