### ISSUE TITLE
Minimap setting does not reflect current state

### ISSUE THREAD

**Issue by blaugold** [invertase/zapp.run#27]
The minimap toggle initially does not reflect the actual visibility of the minimap.
After toggling between on and off it works correctly.

![Screenshot 2022-07-04 at 20 03 22](https://user-images.githubusercontent.com/5929595/177201763-42aae83c-6453-48b9-bde7-b83c32217573.png)

**Comment by Salakar** [comment]
As discussed on slack I've binned this off entirely, it's not a particularly useful feature right now and takes up valuable screen space

Will close for now
