### ISSUE TITLE
It's unclear to me what the save button does exactly

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/zapp.run#3]
![image](https://user-images.githubusercontent.com/24459435/175011918-cb854d73-5a53-4d3e-8d86-bf4b457432a1.png)

When using Zapp! it is unclear to me what happens when I press the save button. I asked me the following questions:
* Where will it be saved?
* Saves this the project locally?
* Saves this the project in my GitHub profile? 

I would expect maybe a one sentence explanation as tooltip when hovering with the mouse over the save button.

**Comment by Ehesp** [comment]
Closing - have updated the tooltip & icon to help. Will reopen if we continue to get similar feedback.
