### ISSUE TITLE
Embedding a Zapp

### ISSUE THREAD

**Issue by Ehesp** [invertase/zapp.run#31]
Once out of EAP, we'll enable a single Zapp project to be embedded onto any website via an iframe with customisable options:

- Control the theme
- Lazy load (blocked loading until the user interacts with the iframe)
- ....?

**Comment by leisim** [comment]
Ideally also an option to remove most UI elements for example for Zapp embedded into documentation.

**Comment by Ehesp** [comment]
There will be a split query parameter to determine the split between editor and preview. This can be set to 0 to show the preview , or 100 to show just the editor, 50 for split down the middle (etc)

There will also be no left menu, instead a small menu icon to open the side menu with just the project info + file editor.

**Comment by leisim** [comment]
Will it be possible to run the build runner automatically? Or at least have a button to run it? For example readers of a documentation embedding Zapp might get confused otherwise.

**Comment by Ehesp** [comment]
You can see how it's starting to shape up here:

https://zapp.run/embed/flutter

Obviously this won't work yet for embedding while in EAP - but feedback welcome!

For example, you can do:

https://zapp.run/embed/flutter?split=0 - preview only
https://zapp.run/embed/flutter?split=100 - editor only
https://zapp.run/embed/flutter?theme=light - forced theme (vs user default)

These will be automatically added to the URL preview in the UI but you get the idea.

**Comment by Salakar** [comment]
Hey everyone, this feature is now live, thanks!
