### ISSUE TITLE
Support git for pubspec packages

### ISSUE THREAD

**Issue by salihgueler** [invertase/zapp.run#32]
Great work team! You can find the related information below. 

**Project ID (e.g. `flutter-123456`)**: flutter-z6406tg6506
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: macOS Monterey 12.4
**Browser & Version (e.g. `Chome 102.0.5005.115`)**: Chrome Version 103.0.5060.114 (Official Build) (arm64)

### Description

When I try to fetch some library references with git, it waits to fetch them around 120 seconds and fails. I assume it causes a time out.

**Comment by Salakar** [comment]
Git refs currently not supported, however it should be fairly trivial to support public repositories for git refs so will add support for this early next week

**Comment by salihgueler** [comment]
> Git refs currently not supported, however it should be fairly trivial to support public repositories for git refs so will add support for this early next week

Public repos should be enough for my use case. It could help me out showcasing some great stuff!

**Comment by Salakar** [comment]
> > Git refs currently not supported, however it should be fairly trivial to support public repositories for git refs so will add support for this early next week
> 
> Public repos should be enough for my use case. It could help me out showcasing some great stuff!

Cool, I'll ship this on Tuesday

**Comment by salihgueler** [comment]
This seems to be working now. I can close it.

**Comment by Salakar** [comment]
Yep sorry forgot to reply back here, but I shipped this on Tuesday :)
