### ISSUE TITLE
Enable Ctrl+S

### ISSUE THREAD

**Issue by slovnicki** [invertase/zapp.run#34]
**Is your feature request related to a problem? Please describe.**
I often press Ctrl+S while developing, but in Zapp I just get a native popup to save the html file.

**Describe the solution you'd like**
It would be great to have Ctrl+S do what "Save" button does.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by Ehesp** [comment]
Ah this is currently bound to the metakey + S, which works on Mac.

I guess on Windows + Others this would be Ctrl + S.

**Comment by jkoenig134** [comment]
For me `ctrl + s` works on Windows. 

(Chrome 103 + Windows 11)

**Comment by Ehesp** [comment]
New update deployed recently with this change, will wait for some more feedback before closing.
