### ISSUE TITLE
Menus not closing on Safari

### ISSUE THREAD

**Issue by DFelten** [invertase/zapp.run#37]
**Operating System & Version**: iPad 11" with iOS 15.5
**Browser & Version**: Safari and Chrome on iPad

### Description

Currently it's not possible to close the three dot context menu with the GitHub, Twitter and other social links. A second tap on the three dots does nothing.

![image](https://user-images.githubusercontent.com/1169185/179098633-80c9e350-42fc-4e35-8509-0b04a2612aad.png)

**Comment by Ehesp** [comment]
Does clicking/pressing on outside of the menu close it (it should). Pressing the dots again should close it, so I'll investigate that.

Thanks!

**Comment by Ehesp** [comment]
Just deployed a fix for this - let me know if it's working (if not I'll reopen)

**Comment by DFelten** [comment]
@Ehesp Thanks for the quick response. The bug is still there with the current live version.

https://user-images.githubusercontent.com/1169185/179452872-3fa03cfa-27fa-4146-99ae-c580741adc48.MOV

**Comment by Ehesp** [comment]
Okay this is actually a Safari issue rather than being specific to iPad - I can replicate locally (just no idea why it happens :D)

**Comment by Ehesp** [comment]
Have just pushed a fix for this - will get it deployed soon. Thanks for the report.
