### ISSUE TITLE
Weird overflow issue

### ISSUE THREAD

**Issue by Mravuri96** [invertase/zapp.run#38]
**Operating System & Version (e.g. `macOS Ventura 13.0`)**:
**Browser & Version (e.g. `Safari 16.0 (18614.1.19.1.5)`)**:

### Description

https://user-images.githubusercontent.com/28457922/179120208-8aca981d-f76c-4264-ba79-5775f259aedb.mov

**Comment by Ehesp** [comment]
Ah I know what this will be, quick fix so will sort today.

**Comment by Ehesp** [comment]
Just deployed a fix, thanks for the report
