### ISSUE TITLE
Support hosted preview urls (e.g. share a preview only url)

### ISSUE THREAD

**Issue by paurakhsharma** [invertase/zapp.run#39]
**Is your feature request related to a problem? Please describe.**
I would like to share an app with my friends without code i.e share the app preview.

**Describe the solution you'd like**
A public link can be used by anyone without a Zapp account and renders the project's output without the source code tab. Just like a web app.

**Additional context**
As discussed [here](https://www.reddit.com/r/FlutterDev/comments/vyu2z8/comment/ig4u7sg/?utm_source=share&utm_medium=web2x&context=3)
I do not have access to Zapp yet so I am not sure if this is already possible. If it is already possible can't wait to try it out. 

Regardless this feature is there or not I am super excited to try Zapp 🚀

**Comment by Ehesp** [comment]
Hey, yes this is definitely on our radar - we're just figuring out the best approach. Few ways to do it so just exploring the fastest.

**Comment by paurakhsharma** [comment]
Thank you for the quick response. That sounds amazing!. Now waiting for my beta invite 🤞

**Comment by Salakar** [comment]
> Thank you for the quick response. That sounds amazing!. Now waiting for my beta invite 🤞

@paurakhsharma Sent you one a few minutes ago 🙃

**Comment by paurakhsharma** [comment]
Got it, thank you 😊

**Comment by Salakar** [comment]
This is coming real soon, we've built a new setup for previews that's blazin' fast, you can test it out via `https://<projectId>.zapp.page`, e.g. https://flutter.zapp.page - for the `flutter` project template - we've still got some work to do with assets before we ship it to be used in the main editor - the remaining work will also fully enable #25 (🎉 )

**Comment by Salakar** [comment]
This is now live, thanks!
