### ISSUE TITLE
Add support for dart-only projects

### ISSUE THREAD

**Issue by schultek** [invertase/zapp.run#40]
**Is your feature request related to a problem? Please describe.**
Zapp always thinks you are building a Flutter app, even if you remove the flutter dependency and import e.g. `dart:html`.

**Describe the solution you'd like**
A separate mode or project setup for Dart-only apps without the dependency on Flutter. Something in the direction of how in DartPad you can choose between Dart vs Flutter when creating a new project.

**Describe alternatives you've considered**
I tried around with just going with it and importing `dart:html` and other dart-only packages. This kinda works but is really unstable, there are always flutter-bits popping up in the console and analyzer.

**Additional context**
My main use-case is to use [jaspr](https://github.com/schultek/jaspr) together with Zapp. In the future I might host examples and demos of this web framework on Zapp, but this requires better support for Dart-only web apps.

**Comment by schultek** [comment]
1. I definitely like the "other features", thats what for me makes the difference between a great online ide and a simple editor like DartPad.

2. I think I would find a separate url more confusing than a simple dropdown when creating a new project.

**Comment by Ehesp** [comment]
Dart-only mode is now supported! 

https://zapp.run/edit/dart

Note; we'll update the website soon to enable selecting Dart vs Flutter :)
