### ISSUE TITLE
Dependency Overrides is not supported on pubspec.yaml

### ISSUE THREAD

**Issue by salihgueler** [invertase/zapp.run#45]
**Is your feature request related to a problem? Please describe.**
When users use dependency overrides for pubspec.yaml with git references, it does not seem to be working.

**Describe the solution you'd like**
One should be able to use pubspec.yaml in the same way they use it on the IDE. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by salihgueler** [comment]
I can show but not share here. :( I can show it in person or we can close this issue. Because I am aware that I am not the most helpful now :)

**Comment by Salakar** [comment]
> I can show but not share here. :( I can show it in person or we can close this issue. Because I am aware that I am not the most helpful now :)

Feel free to dm me on Twitter if you can share that way (@mikediarmid)
