### ISSUE TITLE
hot reload on save

### ISSUE THREAD

**Issue by anilcngz** [invertase/zapp.run#46]
**Is your feature request related to a problem? Please describe.**
It'd be useful if the app is reloaded when we save it as in VS Code.  

**Describe the solution you'd like**
Hot reload on save like in vs code.

**Comment by Ehesp** [comment]
Cmd/Ctrl + R - probably need to make these shortcuts more obvious!

**Comment by hariprasadms** [comment]
> Ctrl + R - probably need to make these shortcuts more obvious!

Yes. I think these kind of shortcuts make them available as button on UI screen would be great ( This is inline with my earlier ticket related to refresh button ). I hoe you can plan for them sooner.

**Comment by UsamaKarim** [comment]
> ![image](https://user-images.githubusercontent.com/842078/179234167-c210fb8d-3e60-44f4-9763-f67f408a7f99.png)
> 
> Would a button which triggers a dialog be obvious enough? Just wondering where to put them 😄


Maybe popup menu is a right place
![Screenshot 2022-07-15 at 7 57 22 PM](https://user-images.githubusercontent.com/64292174/179249593-f24f5401-70cc-478b-a9c5-02ce7658a3d0.png)

**Comment by Ehesp** [comment]
Deployed an update - should show in the footer now. Can move it around easily if it works better in the header menu
