### ISSUE TITLE
Can't Delete a file

### ISSUE THREAD

**Issue by MohamedShMahad** [invertase/zapp.run#47]
**Project ID ( `flutter-zx6067nx706`)**: 
**Operating System & Version (`Windows 10`)**:
**Browser & Version ( `Chrome Version 103.0.5060.114 (Official Build) (64-bit)`)**:

### Description

![Screenshot (68)](https://user-images.githubusercontent.com/64413178/179342305-7ffdb2d9-4a25-4242-a030-71d6fa7aced9.png)

**Comment by Ehesp** [comment]
Do you get any errors showing in browser console?

**Comment by Ehesp** [comment]
Ah, I can replicate the issue - will investigate.

**Comment by Ehesp** [comment]
@MohamedShMahad How did you create the file?

**Comment by Ehesp** [comment]
Thanks, just deployed a fix for this
