### ISSUE TITLE
Add option to change the main entry-point (supporting monorepos)

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/zapp.run#5]
Imagine you have a folder structure like the [FlutterFire](https://github.com/firebase/flutterfire) repo. It would be nice to set the main entry-point so you are able to run code from monorepos (like specifying the `-t` argument for the `flutter run` command).

At the moment, it's forced to the `lib/main.dart`

**Comment by Salakar** [comment]
Compiler support + VS Code lens support for this is in place now and live;

For example, once analyzer has finished loading on https://zapp.run/edit/flutter you should be able to go to `test/my_app_test.dart` and click the `Run Tests` code action appearing above the main function and the tests will run.
![image](https://user-images.githubusercontent.com/5347038/177200823-687181f9-b31f-4825-85a3-d78e994019db.png)
![image](https://user-images.githubusercontent.com/5347038/177200843-aa63ea15-b9d6-4a63-9c8d-4c66815af92a.png)

--- 

This isn't the final UI flow but I wanted to push something for it to be tried out. We'll expand the UI to have an auto-populating dropdown selector of automatically detected entry points (even before analyzer ready) next to the run button, defaults to `lib/main.dart` and/or the last ran entrypoint

**Comment by nilsreichardt** [comment]
Awesome! 😍

**Comment by Salakar** [comment]
Entrypoints selector is now live (also supports specifying entry via URL via `entry` param):

https://user-images.githubusercontent.com/5347038/177622077-b1594cae-ba8a-4861-ba12-ff86186e78f3.mov

Will close this now, appreciate any feedback you may have. UI probably needs a bit more of a polish too 😅

**Comment by nilsreichardt** [comment]
Cool, thanks! 💙
