### ISSUE TITLE
Give a better visual indication for running commands

### ISSUE THREAD

**Issue by TahaTesser** [invertase/zapp.run#52]
I would like to see a clear indication when running commands like run or pub get.
Currently, I see a small circular indicator and it's too fast, appears/disappears very quickly and it looks the same when running the app or executing `pub get`. If I've hidden the preview panel and run the app, I don't have any clear indication if I ran the app.

- I would like to see some text status or colored indication.
- Add a little delay so you can user notice the command is processing. 
When no making changes to the YAML file in VSC and executing pub get still shows status for a second. In Zapp, it is like microseconds of the tiny circular indicator, very easy to miss and not notice so I end up hitting the `pub get` button multiple times.

**Something like this with a minimum delay**

_Circular indicator_  running the app
_Circular indicator_  running `pub get`

Here is a demo 

https://user-images.githubusercontent.com/48603081/179729138-e7485153-8bfd-4116-8e0b-dcbb33fdefb9.mov

**Comment by Ehesp** [comment]
Yeah agree with this one - the activity indicator was initially just meant to show "something is happening".

I was thinking about some form of toast/popup which shows the status of any on-going tasks, and when complete it self removed after a second or so. I'll have a play around and see what the best UI for this could look like.

**Comment by Ehesp** [comment]
If there was instead a status bar which appeared for running tasks (that was closable) but was in the bottom right, would this feel in the way of the preview? For example (hacked in quickly):

![image](https://user-images.githubusercontent.com/842078/180260777-7a9bd558-249d-4c70-a6ee-ac5dd7453ab6.png)

We do have toasts currently but they're more for quick messages such as logging out etc. I could move that to the left, but then I feel like the placement is a bit weird since they don't usually show on the left.

**Comment by Ehesp** [comment]
Alternatively we could also do something like this: 

![image](https://user-images.githubusercontent.com/842078/180261468-6a835c37-f93f-44bf-9de6-f8bc9931d592.png)

In general there's not usually going to be more than one thing going on, but on startup the analyzer takes a while so there could be multiple.

**Comment by TahaTesser** [comment]
> If there was instead a status bar popup which appeared for running tasks (that was closable) but was in the bottom right, would this feel in the way of the preview?

I think so If I am testing a FAB, bottom sheet, or something else positioned at the bottom I would have to wait for the status to disappear. 

I like this https://github.com/invertase/zapp.run/issues/52#issuecomment-1191673357 more, it doesn't get in the way of anything.

**Comment by TahaTesser** [comment]
Could you make it possible to show a popup that shows all the processes running when hovering over or tapping a status with 2 or more processes shown? above https://github.com/invertase/zapp.run/issues/52#issuecomment-1191673357?

**Comment by Salakar** [comment]
We've just shipped beta, please try it out and see if this is better now since there was some changes around this. Thanks
