### ISSUE TITLE
See my Zapp projects

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/zapp.run#53]
In an early version of Zapp it was possible to access all its Zapp projects. As temporary solution for #4 the last has been removed. However, it would be nice to get a list Zapp projects back :)

**Comment by Solido** [comment]
Not sure if I should create a new issue but evocation of search capability makes me think of being able to search like in _stackoverflow_

Name, description and list of labels!

**Comment by Salakar** [comment]
> Not sure if I should create a new issue but evocation of search capability makes me think of being able to search like in _stackoverflow_
> 
> Name, description and list of labels!

Please do

**Comment by Solido** [comment]
Thx!

How to I get there?

404 ERROR

Page not found.
Sorry, we couldn’t find the page you're looking for.

**Comment by Solido** [comment]
Could you just add the `id` in the list.
A way to edit description 
And a CSV export

Sorry to add all this I'm building stuffs on this great products ^^

**Comment by Ehesp** [comment]
Sure thing - I just wanted to roll something out which is simple for now, and iterate on it. 

We've got more time for Zapp now, however we've been mainly investigating improvements to internals and bug fixes. There's been a bunch of work which has been done recently to support things like profile pages.

**Comment by Solido** [comment]
Yeah got it, please see my response as enthusiasm for the product.

I'm already invested in it and integration requests are already there from the community.

Thanks to the team.

**Comment by Ehesp** [comment]
If you're interested, I'd love to have a call with you and discuss use-cases and general thoughts. Hit me up on [Twitter](https://twitter.com/elliothesp) if you have it & are interested.
