### ISSUE TITLE
Stack or Positioned bug?

### ISSUE THREAD

**Issue by davidmgallardo** [invertase/zapp.run#57]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description

Hi, I detected a probably bug in Stack Widget or Positioned Widget.  I maked a Container with height: 250. Inside I put a Stack with an image and an icon. The icon in bottom: 15, right: 15. The icon not put in the correct position, it put in bottom of screen instead of in bottom of the image.
Thanks for the hard work of make this wonderful tool.

**Comment by Ehesp** [comment]
Please can you show screenshots / code / the project ID so we can investigate

**Comment by davidmgallardo** [comment]
Of course.

```
import 'package:flutter/material.dart';

class Detail extends StatelessWidget {
  const Detail({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(color: Colors.white),
      height: 240,
      child: Stack(
        children: [
            Image.network("https://media.istockphoto.com/photos/luxury-resort-picture-id104731717?k=20&m=104731717&s=612x612&w=0&h=40INtJRzhmU1O4Rj24zdY8vj4aGsWpPaEfojaVQ8xBo=",fit: BoxFit.fill),
            Positioned(
              bottom: 15, right: 15,
              child: Icon(Icons.favorite),
            ),
        ],
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
It's not a Zapp bug but rather a mistake in your snippet

The solution is to wrap `Stack` inside a `Center`: 

```dart

class Detail extends StatelessWidget {
  const Detail({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(color: Colors.white),
      height: 240,
      child: Center(
        child: Stack(
          children: [
              Image.network("https://media.istockphoto.com/photos/luxury-resort-picture-id104731717?k=20&m=104731717&s=612x612&w=0&h=40INtJRzhmU1O4Rj24zdY8vj4aGsWpPaEfojaVQ8xBo=",fit: BoxFit.fill),
              Positioned(
                bottom: 15, right: 15,
                child: Icon(Icons.favorite),
              ),
          ],
        ),
      ),
    );
  }
}
```
![Screenshot 2022-07-22 at 15 12 54](https://user-images.githubusercontent.com/20165741/180446405-a307d72b-1d65-4930-b806-1ec0309a7e7c.png)

**Comment by davidmgallardo** [comment]
Wrap Stack inside a Center should not be necessary. I have tested it in visual studio code and it works well without Center.

**Comment by rrousselGit** [comment]
The behavior of Zapp is strictly identical to that of Dartpad

Are you sure that the way you tested in VScode is the same than the way you did on Zapp? To begin with, your problem seems to occur due to the lack of a Scaffold. Maybe when you tested on mobile, you added one

**Comment by davidmgallardo** [comment]
No, the Scaffold is added too in Zapp in the same way as VScode. I made a widget that return the Stack. It is rare what happens.
I attach part of the code where you will can see the call to widget detail. You will see that has a Scaffold:

```
...
class _HomeState extends State<Home> {
  int _currentPage = 0;
  final _pageController = PageController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        controller: _pageController,
        children: [
          
          BasicExample(),
          AnimationDemo(),
          Detail(),
          Container(color: Colors.orange),
        ],
        onPageChanged: (index) {
          setState(() => _currentPage = index);
        },
      ),
...
```

detail.dart:

```
import 'package:flutter/material.dart';

class Detail extends StatelessWidget {
  const Detail({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(color: Colors.white),
      height: 240,
      child: Stack(
        children: [
            Image.network("https://media.istockphoto.com/photos/luxury-resort-picture-id104731717?k=20&m=104731717&s=612x612&w=0&h=40INtJRzhmU1O4Rj24zdY8vj4aGsWpPaEfojaVQ8xBo=",fit: BoxFit.fill),
            Positioned(
              bottom: 15, right: 15, //give the values according to your requirement
              child: Icon(Icons.favorite),
            ),
        ],
      ),
    );
    

  }
}
```

**Comment by blaugold** [comment]
This is expected behavior.

The `PageView` forces the `Container` in `Detail` to fill the page. In turn, the `Container` forces the `Stack` to fill the page. So, the `Icon` in the `Positioned` ends up at the bottom right of the page.

The `Stack` also forces any unpositioned children to fill the space the `Stack` occupies. If the space `Image` needs to fill is larger than the displayed image, it will fit the image with [`BoxFit.scaleDown`](https://api.flutter.dev/flutter/painting/BoxFit.html).

If the image is large enough, it might work on certain screen sized accidentally.

**Comment by davidmgallardo** [comment]
I get it! I will have that in mind. Thanks for your time.
