### ISSUE TITLE
Scroll is not properly working on iPad (safari)

### ISSUE THREAD

**Issue by immadisairaj** [invertase/zapp.run#59]
I tried to run on iPad. It was basic entry application. I was just trying to scroll, which doesn't and instead selects text.

**Project ID (e.g. `flutter-123456`)**: Not Required
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: iPadOS 15.6
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Safari

### Description

Scroll is not happening properly. 
I am not sure if this might be related to #37.

The scroll doesn't happen with either touch or Apple Pencil.

https://user-images.githubusercontent.com/40348358/180707131-a03e8b87-b284-4d9f-9661-7a6a51faae43.MOV

**Comment by Ehesp** [comment]
@immadisairaj would you be able to try on this: https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

It's the same base editor we use so wondering if it's just a general issue with touch devices (which don't seem that well supported)

**Comment by immadisairaj** [comment]
I tried to load the screen of the editor, it was working fine when I use finger to swipe.

Same thing with Zapp also. It works perfectly fine.

The problem I think is, when I first used Apple Pencil to scroll, it's assuming text and selecting and instead of scroll.

Then when I shifted to finger, you can see the accessibility control for Apple Pencil is still there (from video) and not scrolling.

So, I think the problem is when we start using Apple Pencil.

**Comment by Ehesp** [comment]
Ok going to close this one off, not sure there is much else I can do to support Apple Pencil. This would be something which Monaco needs to support.

Thanks!
