### ISSUE TITLE
Safari errors

### ISSUE THREAD

**Issue by ened** [invertase/zapp.run#60]
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: macOS 12.4 (21F79)
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Safari Version 15.5 (17613.2.7.1.8)

### Description

At the moment, opening files for editing is not working for me - the menus stop responding as well after a while.

I didn't see a page for "supported browsers", is Safari one of them?

![Screenshot 2022-07-25 at 09 07 12](https://user-images.githubusercontent.com/269860/180729409-b72e21b9-cd42-4cca-9b3c-e59dab3f845a.png)

**Comment by Ehesp** [comment]
Hey, Safari should be (or at least intended to be) supported - got a few bugs with it though in regards to the Ui which I'm bashing my head over.

- The 404 errors are expected (need to remove the sourcemaps link from the JS code)

As for the other errors, can you try a cached refresh? I'm not seeing those myself so trying to figure out why they would happen. Is the URL just the `/edit/flutter` url?

**Comment by Ehesp** [comment]
Oh I see - creating a menu and then clicking a file is throwing those other errors. Will investigate.

**Comment by Ehesp** [comment]
Just deployed an update - can you see if this solves your issues? Thanks

**Comment by ened** [comment]
Better, but code is still not loading.

<img width="1462" alt="Screenshot 2022-07-26 at 14 12 32" src="https://user-images.githubusercontent.com/269860/181014254-0e20840d-a3c6-4320-a61e-6a34726f687d.png">

**Comment by Ehesp** [comment]
What version of Safari are you on? 

I'm on Version 15.2 (17612.3.6.1.6) with no issues. Struggling to replicate :(

**Comment by Ehesp** [comment]
Can you try to disable adblock if it's running? No idea if it's related: https://github.com/niklasvh/html2canvas/issues/1416

**Comment by ened** [comment]
Yes, JSON Peep is the issue. I removed it and the page loads as expected.

**Comment by Ehesp** [comment]
I'll close the issue for now, although happy to discuss. Not entirely sure what can be done to fix this though (?)
