### ISSUE TITLE
"Rename symbol" right-click option & "F2" keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by GroovinChip** [invertase/zapp.run#63]
**Project ID (e.g. `flutter-123456`)**: Build ID: ec86565a-af97-4151-873e-8d93bb12ca81
**Operating System & Version**: `macOS Monterey 12.4`
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Chrome Version 103.0.5060.134 (Official Build) (arm64)

### Description

The "Rename symbol" right-click option & "F2" keyboard shortcut doesn't work - nothing happens when doing these actions

**Comment by Ehesp** [comment]
Thanks - rename symbol is a known issue we have internally; we know what the issue is just not sure how to fix it yet.

Wasn't aware F2 also triggered this command, and looks like it's not being handled at all so I'll investigate that.

**Comment by Salakar** [comment]
We pushed a silent update live today which fixes this and a bunch of other issues. Please try it out. Thanks!
