### ISSUE TITLE
IOS testing for flutter

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [invertase/zapp.run#64]
Currently Zapp supports only web. This should at least support one other OS like Mac.

**Comment by Ehesp** [comment]
This is planned, but not for a long time. 

Our main focus for now is delivering a good experience for web, with a rich feature set. Introducing remote builds isn't our priority right.

**Comment by UmairSaqibBhutta** [comment]
You are absolutely right and doing a very great job for people but today's main issue is the unavailability of Mac for flutter developers, if solved then it will be more beneficial than the web experience.
