### ISSUE TITLE
Please add support to run my existing projects from github

### ISSUE THREAD

**Issue by Musaddiq625** [invertase/zapp.run#67]
**Add support to run my existing projects from Github**
Ive one of my project I want to run directly on zapp, Ive never ran my project on zapp
Right now I cant connect my github account to zapp (Image attached)
![image](https://user-images.githubusercontent.com/37911054/185713460-15826ebe-bb84-4902-814a-ac281e8e91c7.png)

**Add a button or something**
Add a button to sync or add a button to add the project from the connected github account.

Thank you

**Comment by Salakar** [comment]
This is planned but closing this issue as its a duplicate of #55 - thanks
