### ISSUE TITLE
Autostart editor as url parameter

### ISSUE THREAD

**Issue by Solido** [invertase/zapp.run#71]
When displayed as embedded a user interaction is required to start the editor.

I would like to have an option in the url to auto-start the editor.

When exploring content it force the users to click again and break the experience.

Does this would have consequences elsewhere?

Thx!

**Comment by Ehesp** [comment]
This is because lazy load is enabled by default:

![image](https://user-images.githubusercontent.com/842078/185927235-80fa2952-ea20-458f-93e3-ad122f57cafb.png)

(the `lazy=true` flag)

The only negative here is that it'll download everything when the iframe loads, even if its not used on the page.

**Comment by Solido** [comment]
It was in front of me but got there too fast. Thx
