### ISSUE TITLE
Save project with keyboard shortcut

### ISSUE THREAD

**Issue by mhadaily** [invertase/zapp.run#72]
**Is your feature request related to a problem? Please describe.**
I want to save my project with keyboard by shortcuts like command on mac + s or ctrl + s on windows. 

**Describe the solution you'd like**
override the save shortcut from the browser with a custom keyboard interceptor in JS. 

**Describe alternatives you've considered**
Let me add my shortcut

**Comment by alestiago** [comment]
Running the analyser automatically when this occurs would be superb.

**Comment by Salakar** [comment]
This is now live.
