### ISSUE TITLE
Corrupted assets

### ISSUE THREAD

**Issue by ufrshubham** [invertase/zapp.run#76]
**Project ID (e.g. `flutter-123456`)**: flutter-z4606hq4706
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: Windows 11 Version	21H2
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Chrome 104.0.5112.102 (Official Build) (64-bit)

### Description

My project uses some image assets and every time I revisit my project after logging out, the asset files sees to get corrupted. Reuploading the images fixes the problem most of the time. The log just prints [object Event].

**Comment by Ehesp** [comment]
This should be now fixed - unfortunately those assets which are already corrupt may not work, so re-uploading would be the best approach. Sorry about this.
