### ISSUE TITLE
Unexpected analyzer error (Color / Material Color)

### ISSUE THREAD

**Issue by blaugold** [invertase/zapp.run#78]
**Project ID (e.g. `flutter-123456`)**: https://zapp.run/edit/flutter-zx1406y7x150?entry=lib/main.dart&file=lib/main.dart
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: macOS Monterey 12.5.1 
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Chrome 104.0.5112.101

### Description

The analyzer displays an error when trying to assign a `MaterialColor` to a `Color`. This should be fine since `MaterialColor` extends `Color` and is not an issue locally (with Flutter 3.0.5).

![Screenshot 2022-08-30 at 14 47 17](https://user-images.githubusercontent.com/5929595/187440761-e53c66f8-8cf2-47a7-8eb0-c9181691192f.png)

**Comment by Solido** [comment]
Just came here to share the same feedback.
Message is `'MaterialColor' can't be assigned to the parameter type 'Colors?'`

**Comment by Ehesp** [comment]
This is now fixed 🥳
