### ISSUE TITLE
Its horrible as of now (Images lost,Colors not working )

### ISSUE THREAD

**Issue by Gaurangseven** [invertase/zapp.run#83]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description
I was making a quiz app for past 3 days each time the images used to be lost and errors like object event comes 
Colors.blue is giving errors and if i replace it with Colors.white it works

**Comment by Salakar** [comment]
Closing as duplicate of #76
