### ISSUE TITLE
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE 

### ISSUE THREAD

**Issue by Gaurangseven** [invertase/zapp.run#86]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description
always throws Image exception

**Comment by Ehesp** [comment]
Can you provide some more context please? What code/project etc.

**Comment by Gaurangseven** [comment]
Yeah sure, whenever I try to run the app the images don't show up and give error like  _EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE_  
![Screenshot (63)](https://user-images.githubusercontent.com/83110436/188511169-3e4a6e6a-7a03-43a3-93ec-1b0f8380dccb.png)

which results in errors like image not working and getting things like **Object Event** in place of images  ,which certainly refers to error in compilation during run time

**Comment by Salakar** [comment]
Closing as duplicate of #76
