### ISSUE TITLE
Issues in adding Provider package

### ISSUE THREAD

**Issue by Gaurangseven** [invertase/zapp.run#87]
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description
Issues in adding Provider package

There is a issue in adding providing package to the app even after running pub get its not there

**Comment by Salakar** [comment]
We pushed a silent update live today which fixes this and a bunch of other issues. Please try it out. Thanks!
