### ISSUE TITLE
With Fresh Start Editor Does not open on Firefox

### ISSUE THREAD

**Issue by salihgueler** [invertase/zapp.run#88]
**Project ID (e.g. `flutter-123456`)**: N/A 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: macOS Monterey 12.5.1
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**: Firefox Version 91.13.0esr (64-bit)

### Description

Here are steps to reproduce:

- Open Firefox and go to zapp.run for the first time
- Click on Get Started
Actual:
- The page is stuck with "Loading"
Expected: 
- Editor Opens

On the inspect it shows as error:

```
Uncaught ReferenceError: TransformStream is not defined
    <anonymous> https://zapp.run/assets/index.10207d2f.js:2627
```

**Comment by Ehesp** [comment]
@salihgueler I'm not seeing this, what version of Firefox are you running?

![image](https://user-images.githubusercontent.com/842078/204319867-b7c42a3f-0e43-4327-bd5e-093f572da587.png)

Could you try it in a private window to make sure it's not a plugin/extension?

**Comment by Ehesp** [comment]
Going to close this, seems to be ok here. Please let me know if you still have issues!
