### ISSUE TITLE
Clicking on the Embed button does not show the files of my Zapp

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/zapp.run#9]
**Project ID (e.g. `flutter-123456`)**: `flutter-z8006cm810`
**Operating System & Version (e.g. `macOS Monterey 12.1`)**: `12.2.1 (21D62)`
**Browser & Version (e.g. `Chome 102.0.5005.115`)**: `Chrome 102.0.5005.115 (Official Build) (arm64)`

### Description

https://user-images.githubusercontent.com/24459435/175085470-40db0ec8-4002-45ea-b410-b02764e74f1f.mov

You can see in the video that in the menu for the embed button the default files are shown.

I would expect to see in the embed menu my file from my Zapp project.

**Comment by Ehesp** [comment]
https://github.com/invertase/zapp.run/issues/31

**Comment by Ehesp** [comment]
Note; embedding is currently disabled whilst in EAP.

**Comment by Salakar** [comment]
This is now resolved on the latest beta release that is now live, thanks :)
