### ISSUE TITLE
zapp doesn't recognize `SelectionArea` widget.

### ISSUE THREAD

**Issue by Biplab-Dutta** [invertase/zapp.run#92]
**Project ID**: flutter-zi2060ai306 
**Operating System & Version**: Fedora 36
**Browser & Version**: Microsoft Edge 106.0.1370.47 (64-bit)

### Description
I was trying to run a quick sample Flutter code on zapp. The code had a `SelectionArea` widget. For some reason, the IDE doesn't recognize the `SelectionArea` widget. The same code works without any issue when ran on vs code.

![image](https://user-images.githubusercontent.com/63902683/196208630-e9f69c10-f40a-4d9c-af08-4cf68253306a.png)

**Comment by Ehesp** [comment]
If you compile, does it actually work? Wondering whether this is more of an analyzer issue.

**Comment by Biplab-Dutta** [comment]
@Ehesp I remember it not working. So, I had to use VS Code.

**Comment by Ehesp** [comment]
Ok thanks - will investigate.

**Comment by Biplab-Dutta** [comment]
Thank you.. 🥳
