### ISSUE TITLE
Go to Defination Not working

### ISSUE THREAD

**Issue by rgtstha** [invertase/zapp.run#93]
**Project ID (`flutter-zb206n6b306`)**: 
**Operating System & Version (`macOS Monterey 12.6`)**:
**Browser & Version (e.g. `Chrome 106.0.5249.119 `)**:

### Description

Right clicking on any widget and clicking `Go To Defination` not working. See the attachment below.

https://user-images.githubusercontent.com/24633117/199419143-88d5a8ae-1b09-44fc-90b7-5a860f94551d.mov

**Comment by Ehesp** [comment]
Ok we've identified the issue, just need to figure out how to fix it now :D

**Comment by Salakar** [comment]
We pushed a silent update live today which fixes this and a bunch of other issues. Please try it out. Thanks!

**Comment by rgtstha** [comment]
Perfect. Working fine now.
