### ISSUE TITLE
Stop button: to stop execution

### ISSUE THREAD

**Issue by ben-xD** [invertase/zapp.run#96]
My main function finished, but my program still ran because of a bug in **my** code. However, there was no easy way to stop the program, like a stop button. Even after refreshing the page, the **Network tab logs** indicated my program was still running.

I had to make changes to the code and re-run to stop the logs.

Here's my project: https://zapp.run/edit/dart-z6m06gu6n06?lazy=false&split=50&entry=lib/main.dart&file=lib/main.dart
- It uses http to check for network connectivity, and I wasn't cleaning up (and I **noticed the network tab was still making requests**).

Might be related to https://github.com/invertase/zapp.run/issues/81

Side note: i seem to remember reading a kanban board of planned features/bug fixes. I can't find it now.

**Comment by Ehesp** [comment]
Thanks for the project link , we'll take a look at how we can handle this. I think there was a issue for being able to stop an in progress build rather than the process, so different to this one

**Comment by Ehesp** [comment]
I think with the page refresh it's running because we execute on load so it'll have just started again.

**Comment by Salakar** [comment]
@ben-xD project board is here: https://github.com/orgs/invertase/projects/16

**Comment by Ehesp** [comment]
This is now live - please let me know any feedback!
