### ISSUE TITLE
Project not running 

### ISSUE THREAD

**Issue by martie1983** [invertase/zapp.run#97]
Flutter Project not running in any browser even for the first time..I logged in using Github..
the following are errors..
[
{
"code": "invalid_type",
"expected": "string",
"received": "null",
"path": [
"owner",
"display_name"
],
"message": "Expected string, received null"
}
]
unable to save project

**Comment by Ehesp** [comment]
Hey, is this just using /edit/flutter or is it a forked project you own? Can you share the id if so?

**Comment by Ehesp** [comment]
OK thanks I'll take a look soon, I think I know what the issue is.

**Comment by martie1983** [comment]
sure..thx

**Comment by martie1983** [comment]
thx a lot..   for now its working..  I will check for two days and close this issue..
