### ISSUE TITLE
Multiline strings are reversed

### ISSUE THREAD

**Issue by puf** [invertase/zapp.run#99]
### Description

Given this code:

    void main() {
      var s = """A
    multi-line
    string""";
      print(s);
    }

The output of [running it on Dartpad](https://dartpad.dartlang.org/?id=41e977065e53d3fe14a8a0b62938806c) is:

    A
    multi-line
    string

While [running it on Zapp.run](https://zapp.run/edit/z97206a69730?lazy=false&split=50&entry=lib/main.dart&file=lib/main.dart:0-65) gives this output:

    [15:43:32] string
    [15:43:32] multi-line
    [15:43:32] A

While I love myself some yoda speak, the Dartpad interpretation seems more logical. ;-)

**Comment by Ehesp** [comment]
Fix it, I will.

This may be a CSS thing, I believe I'm using flex reverse to push the output to the bottom and scroll down when more is added.

**Comment by Ehesp** [comment]
Alright after almost throwing my computer out of the window trying to get flexbox reverse working well with this issue + forcing the container to keep scrolled to the bottom I decided to just do what makes sense on the web. Logs now come in at the top and fall downwards, like a normal scroll container 🧯
